version: '3'
services:
  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: ./dockers/Dockerfile.prod
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/build
    env_file:
      - ./environment/env.production
    ports:
      - "8080:80"

